apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>prod</title>
    </head>
    <body>

    <h1>YES AutoPromoted-FAIL-AGAIN</h1>


    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
