apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>test</title>
    </head>
    <body>

    <h1>Autopromoted!</h1>
    <h1>And tested!</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
